service: Health-Event-Jira-Automation
 
provider:
  name: aws
  runtime: python3.11
  region: us-east-1
 
functions:
  health:
    handler: health.lambda_handler
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - "aws.health"
 
resources:
  Resources:
    MyEventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: AWS-Health-EventRule
        EventBusName: default
        EventPattern:
          source:
            - "aws.health"
 
    
